// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: map/v1/map.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFeatureRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// GeoJSON Geometry or Feature object as JSON text, e.g. {"type":"Point","coordinates":[116.4,39.9]}
	Geojson       string `protobuf:"bytes,3,opt,name=geojson,proto3" json:"geojson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeatureRequest) Reset() {
	*x = CreateFeatureRequest{}
	mi := &file_map_v1_map_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeatureRequest) ProtoMessage() {}

func (x *CreateFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_map_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeatureRequest.ProtoReflect.Descriptor instead.
func (*CreateFeatureRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_map_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeatureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFeatureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFeatureRequest) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

type GetFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureRequest) Reset() {
	*x = GetFeatureRequest{}
	mi := &file_map_v1_map_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureRequest) ProtoMessage() {}

func (x *GetFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_map_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureRequest.ProtoReflect.Descriptor instead.
func (*GetFeatureRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_map_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeatureRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageOffset    int32                  `protobuf:"varint,2,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesRequest) Reset() {
	*x = ListFeaturesRequest{}
	mi := &file_map_v1_map_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesRequest) ProtoMessage() {}

func (x *ListFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_map_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesRequest.ProtoReflect.Descriptor instead.
func (*ListFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_map_proto_rawDescGZIP(), []int{2}
}

func (x *ListFeaturesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFeaturesRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Geojson       string                 `protobuf:"bytes,4,opt,name=geojson,proto3" json:"geojson,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_map_v1_map_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_map_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_map_v1_map_proto_rawDescGZIP(), []int{3}
}

func (x *Feature) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

func (x *Feature) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Feature) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListFeaturesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*Feature             `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesReply) Reset() {
	*x = ListFeaturesReply{}
	mi := &file_map_v1_map_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesReply) ProtoMessage() {}

func (x *ListFeaturesReply) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_map_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesReply.ProtoReflect.Descriptor instead.
func (*ListFeaturesReply) Descriptor() ([]byte, []int) {
	return file_map_v1_map_proto_rawDescGZIP(), []int{4}
}

func (x *ListFeaturesReply) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_map_v1_map_proto protoreflect.FileDescriptor

const file_map_v1_map_proto_rawDesc = "" +
	"\n" +
	"\x10map/v1/map.proto\x12\x06map.v1\x1a\x1cgoogle/api/annotations.proto\"f\n" +
	"\x14CreateFeatureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\ageojson\x18\x03 \x01(\tR\ageojson\"#\n" +
	"\x11GetFeatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x13ListFeaturesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x02 \x01(\x05R\n" +
	"pageOffset\"\xa7\x01\n" +
	"\aFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\ageojson\x18\x04 \x01(\tR\ageojson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"@\n" +
	"\x11ListFeaturesReply\x12+\n" +
	"\bfeatures\x18\x01 \x03(\v2\x0f.map.v1.FeatureR\bfeatures2\x9d\x02\n" +
	"\x03Map\x12[\n" +
	"\rCreateFeature\x12\x1c.map.v1.CreateFeatureRequest\x1a\x0f.map.v1.Feature\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/map/features\x12W\n" +
	"\n" +
	"GetFeature\x12\x19.map.v1.GetFeatureRequest\x1a\x0f.map.v1.Feature\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/map/features/{id}\x12`\n" +
	"\fListFeatures\x12\x1b.map.v1.ListFeaturesRequest\x1a\x19.map.v1.ListFeaturesReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/map/featuresB0\n" +
	"\x15dev.kratos.api.map.v1P\x01Z\x15amGraph/api/map/v1;v1b\x06proto3"

var (
	file_map_v1_map_proto_rawDescOnce sync.Once
	file_map_v1_map_proto_rawDescData []byte
)

func file_map_v1_map_proto_rawDescGZIP() []byte {
	file_map_v1_map_proto_rawDescOnce.Do(func() {
		file_map_v1_map_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map_v1_map_proto_rawDesc), len(file_map_v1_map_proto_rawDesc)))
	})
	return file_map_v1_map_proto_rawDescData
}

var file_map_v1_map_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_map_v1_map_proto_goTypes = []any{
	(*CreateFeatureRequest)(nil), // 0: map.v1.CreateFeatureRequest
	(*GetFeatureRequest)(nil),    // 1: map.v1.GetFeatureRequest
	(*ListFeaturesRequest)(nil),  // 2: map.v1.ListFeaturesRequest
	(*Feature)(nil),              // 3: map.v1.Feature
	(*ListFeaturesReply)(nil),    // 4: map.v1.ListFeaturesReply
}
var file_map_v1_map_proto_depIdxs = []int32{
	3, // 0: map.v1.ListFeaturesReply.features:type_name -> map.v1.Feature
	0, // 1: map.v1.Map.CreateFeature:input_type -> map.v1.CreateFeatureRequest
	1, // 2: map.v1.Map.GetFeature:input_type -> map.v1.GetFeatureRequest
	2, // 3: map.v1.Map.ListFeatures:input_type -> map.v1.ListFeaturesRequest
	3, // 4: map.v1.Map.CreateFeature:output_type -> map.v1.Feature
	3, // 5: map.v1.Map.GetFeature:output_type -> map.v1.Feature
	4, // 6: map.v1.Map.ListFeatures:output_type -> map.v1.ListFeaturesReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_map_v1_map_proto_init() }
func file_map_v1_map_proto_init() {
	if File_map_v1_map_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map_v1_map_proto_rawDesc), len(file_map_v1_map_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_map_v1_map_proto_goTypes,
		DependencyIndexes: file_map_v1_map_proto_depIdxs,
		MessageInfos:      file_map_v1_map_proto_msgTypes,
	}.Build()
	File_map_v1_map_proto = out.File
	file_map_v1_map_proto_goTypes = nil
	file_map_v1_map_proto_depIdxs = nil
}
