// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: map/v1/map.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMapCreateFeature = "/map.v1.Map/CreateFeature"
const OperationMapGetFeature = "/map.v1.Map/GetFeature"
const OperationMapListFeatures = "/map.v1.Map/ListFeatures"

type MapHTTPServer interface {
	CreateFeature(context.Context, *CreateFeatureRequest) (*Feature, error)
	GetFeature(context.Context, *GetFeatureRequest) (*Feature, error)
	ListFeatures(context.Context, *ListFeaturesRequest) (*ListFeaturesReply, error)
}

func RegisterMapHTTPServer(s *http.Server, srv MapHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/map/features", _Map_CreateFeature0_HTTP_Handler(srv))
	r.GET("/v1/map/features/{id}", _Map_GetFeature0_HTTP_Handler(srv))
	r.GET("/v1/map/features", _Map_ListFeatures0_HTTP_Handler(srv))
}

func _Map_CreateFeature0_HTTP_Handler(srv MapHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFeatureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapCreateFeature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFeature(ctx, req.(*CreateFeatureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Feature)
		return ctx.Result(200, reply)
	}
}

func _Map_GetFeature0_HTTP_Handler(srv MapHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFeatureRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapGetFeature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFeature(ctx, req.(*GetFeatureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Feature)
		return ctx.Result(200, reply)
	}
}

func _Map_ListFeatures0_HTTP_Handler(srv MapHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFeaturesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMapListFeatures)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFeatures(ctx, req.(*ListFeaturesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFeaturesReply)
		return ctx.Result(200, reply)
	}
}

type MapHTTPClient interface {
	CreateFeature(ctx context.Context, req *CreateFeatureRequest, opts ...http.CallOption) (rsp *Feature, err error)
	GetFeature(ctx context.Context, req *GetFeatureRequest, opts ...http.CallOption) (rsp *Feature, err error)
	ListFeatures(ctx context.Context, req *ListFeaturesRequest, opts ...http.CallOption) (rsp *ListFeaturesReply, err error)
}

type MapHTTPClientImpl struct {
	cc *http.Client
}

func NewMapHTTPClient(client *http.Client) MapHTTPClient {
	return &MapHTTPClientImpl{client}
}

func (c *MapHTTPClientImpl) CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...http.CallOption) (*Feature, error) {
	var out Feature
	pattern := "/v1/map/features"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMapCreateFeature))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapHTTPClientImpl) GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...http.CallOption) (*Feature, error) {
	var out Feature
	pattern := "/v1/map/features/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMapGetFeature))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MapHTTPClientImpl) ListFeatures(ctx context.Context, in *ListFeaturesRequest, opts ...http.CallOption) (*ListFeaturesReply, error) {
	var out ListFeaturesReply
	pattern := "/v1/map/features"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMapListFeatures))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
